### ISSUE TITLE
Can I active pretrained model after 40k steps ?

### ISSUE THREAD

**Issue by medalawi** [Archivoice/Diff-SVC-notebooks#17]
Hi  without using pretrained model I made 40k steps  , now I want to use  nyaru pertained model and continue training to 100k steps does this make voice better or I have to start from 0 again? Thank you .

**Comment by haru0l** [comment]
Sadly, no. You have to start from (nyaru's) 0 again.  Using the model only speeds up model learning due to it no longer starting from scratch.

**Comment by medalawi** [comment]
Thank you for your reply
