### ISSUE TITLE
how to resume training

### ISSUE THREAD

**Issue by loboere** [Archivoice/Diff-SVC-notebooks#9]
I saved the checkpoint with step 14000 in drive with Step 6: Package Model

then try to continue training by unzipping the zip in /content/diff-svc/checkpoints but the training starts from step 0 or the global step is also 0, how to continue from 14000?

**Comment by Archivoice** [comment]
To resume training from a checkpoint, use step 2-A to decompress the binary data used for training,  remember to set the correct singer name. Then create a folder with the singer name under the following directory like so: `diff-svc/checkpoints/{singer_name}`, place the checkpoint file and config.yaml in said folder then you can resume training.

**Comment by loboere** [comment]
great thanks, another question how to make checkpoints save to google drive instead of /content/diff-svc/checkpoints

**Comment by haru0l** [comment]
Please use the use_save_dir and the save_dir function for that. Put your Google Drive path into the save_dir textbox. Note that you can also resume training this way, by pointing to the same folder.
